### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by vergissberlin** [netresearch/ansible-role-raspberry-pi-monitor#1]
*Acceptance criterias:* 
https://drive.google.com/drive/folders/1O-fmiAw0iKByQ_Usv8mRW0oC8AW1WYaN

**Comment by Normo** [comment]
Hi @TheDevMinerTV 

## code review

- change company to Netresearch DTT GmbH - https://github.com/netresearch/ansible-role-raspberry-pi-monitor/blob/master/meta/main.yml#L5
- Debian Wheezy already reached EOL- https://github.com/netresearch/ansible-role-raspberry-pi-monitor/blob/master/meta/main.yml#L11

- Consider using [`with_items` loop](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html?highlight=loops#standard-loops) to create multiple directories -
  - https://github.com/netresearch/ansible-role-raspberry-pi-monitor/blob/master/tasks/chromium.yml#L8
  - https://github.com/netresearch/ansible-role-raspberry-pi-monitor/blob/master/tasks/chromium.yml#L13
  - https://github.com/netresearch/ansible-role-raspberry-pi-monitor/blob/master/tasks/chromium.yml#L18

- What does this [warning](https://github.com/netresearch/ansible-role-raspberry-pi-monitor/blob/master/README.md#warning) mean? :confused:

**Comment by TheDevMinerTV** [comment]
@Normo I still have 2 Pi's running Raspbian Wheezy. I don't want to upgrade.

**Comment by TheDevMinerTV** [comment]
```yaml
with_items
```
loop is deprecated. It will be removed in Ansible 2.9.

**Comment by Normo** [comment]
@TheDevMinerTV 

> loop is deprecated. It will be removed in Ansible 2.9.

How about https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#migrating-from-with-x-to-loop ?

> I still have 2 Pi's running Raspbian Wheezy. I don't want to upgrade.

But we don't support outdated operating systems.

**Comment by TheDevMinerTV** [comment]
But it's open source and you don't need to use it.
I can still write to this repo, so I can help with issues regarding debian wheezy.
But I don't think that there is someone other than me, who is interested in this repository.

**Comment by Normo** [comment]
Code review done.
